# Change these first
owner: dime-scheduler # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: App
    url: https://app.dimescheduler.com/healthz
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
  - name: API
    url: https://api.dimescheduler.com/healthz    
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
  - name: Database
    url: https://cp.dimescheduler.com/api/database
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
  - name: Services
    url: https://cp.dimescheduler.com/api/healthz    
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.dimescheduler.com
  baseUrl: /status
  logoUrl: https://cdn.dimescheduler.com/dime-scheduler/v2/logo.svg
  themeUrl: https://dime-scheduler.github.io/status/my-custom-theme.css
  name: Dime.Scheduler
  introTitle: "**Dime.Scheduler** is the leading resource and project planning solution for Microsoft Dynamics 365 Business Central"
  introMessage: For more information, [**check out our website**](https://www.dimescheduler.com)
  faviconSvg: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.dimescheduler.com
i18n:
  footer: Dime Software

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
