# Change these first
owner: dime-scheduler # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: App
    url: $APP
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
  - name: API
    url: $API
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
  - name: Database
    url: $DATABASE
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
  - name: Services
    url: $SERVICES
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg

  - name: Docs
    url: https://docs.dimescheduler.com
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg

  - name: Website
    url: https://www.dimescheduler.com
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
    
  - name: App [SANDBOX]
    url: $APPSANDBOX
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
       
  - name: API [SANDBOX]
    url: $APISANDBOX
    icon: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg 
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dimescheduler.com
  #baseUrl: /status
  logoUrl: https://cdn.dimescheduler.com/dime-scheduler/v2/logo.svg
  themeUrl: https://status.dimescheduler.com/my-custom-theme.css
  name: Dime.Scheduler
  introTitle: "**Dime.Scheduler** is the leading resource and project planning solution for Microsoft Dynamics 365 Business Central"
  introMessage: For more information, [**check out our website**](https://www.dimescheduler.com)
  faviconSvg: https://cdn.dimescheduler.com/dime-scheduler/v2/shape.svg
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.dimescheduler.com
    - title: Docs
      href: https://docs.dimescheduler.com
i18n:
  footer: Dime Software

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
